Repository mdnazisharman2803/QuickRead, pull requests merged in 2023-10, with the labels that each got.

#21 Create Design how it work and User Profile UI screen
  Create Design how it work and User Profile UI screen/How it work.png
  Create Design how it work and User Profile UI screen/Log in.png
  Design Homepage, chat, How it work and history UI screen/Chat Screen.png
  Design Homepage, chat, How it work and history UI screen/History.png
  Design Homepage, chat, How it work and history UI screen/Home page.png
Labels: hacktoberfest-accepted

#22 Create LogIn and SignUp Screen. Forget password
  Sign Up and Forget password/Forget Password.png
  Sign Up and Forget password/Register.png
Labels: hacktoberfest-accepted, UI/UX design

#23 Create Onboarding Screen UI
  Onboarding Screen UI. Profile and Splash Screen/Profile.png
  Onboarding Screen UI. Profile and Splash Screen/Splash Screen.png
  Onboarding Screen UI. Profile and Splash Screen/Splash screen 2.png
Labels: hacktoberfest-accepted, UI/UX design

#24 Create UI and UX Experience Design For The Application. (Processing Screen)
  Processing Screen and  Delete chat history screen/Delete Chat history.png
  Processing Screen and  Delete chat history screen/Processing Screen.png
Labels: hacktoberfest-accepted, UI/UX design

#25 Update README.md
  README.md
Labels: hacktoberfest-accepted, UI/UX design

#29 :sparkles: splash screen [Splash screen development]
  flutter_dartified/assets/logo/logo.png
  flutter_dartified/lib/main.dart
  flutter_dartified/lib/screens/export_screens.dart
  flutter_dartified/lib/screens/landing_screen/landing_screen.dart
  flutter_dartified/lib/screens/root.dart
  flutter_dartified/lib/utils/constants/image_constants.dart
  flutter_dartified/lib/utils/export_utils.dart
  flutter_dartified/pubspec.yaml
Labels: hacktoberfest-accepted, development

#31 Update README
  README.md
Labels: documentation, hacktoberfest-accepted

#36 :sparkles: refactored code + add login screen [FRONTEND - Development: Login screen]
  flutter_dartified/assets/logo/subLogo.png
  flutter_dartified/lib/config/customRouter.dart
  flutter_dartified/lib/config/routes.dart
  flutter_dartified/lib/main.dart
  flutter_dartified/lib/screens/auth_screens/login_screen.dart
  flutter_dartified/lib/screens/auth_screens/registration_screen.dart
  flutter_dartified/lib/screens/export_screens.dart
  flutter_dartified/lib/screens/landing_screen/landing_screen.dart
  flutter_dartified/lib/utils/constants/image_constants.dart
  flutter_dartified/lib/utils/extensions/extensions.dart
  flutter_dartified/lib/widgets/auth_widgets/auth_textfield_widget.dart
  flutter_dartified/lib/widgets/common_widgets/custom_button.dart
  flutter_dartified/lib/widgets/export_widgets.dart
Labels: hacktoberfest-accepted, development
